#### image sizes of datasets

In [1]:
import os
import time
import subprocess
from pathlib import Path
from PIL import Image
from tqdm import tqdm

import pandas as pd

In [4]:
""" 1. CLIC """
dataset_dir = '/media/ps/ssd6/zhaoy/datasets/clic/mobile/valid'
dataset_dir = Path(dataset_dir)

images = list(dataset_dir.glob('*.png'))
rows = []
for image in images:
    with Image.open(image) as I:
        width, height = I.size
        npixels = width * height
        rows.append([image.name, width, height, npixels])
        
df = pd.DataFrame(rows, columns=['image', 'width', 'height', 'npixels'])
display(df)
display(df.describe())

                                      image  width  height  npixels
0    e58eeecc69309177f30808d671d08a55.png   1512    2016  3048192
1    1b8c4dc594ba04518bbd959d339806e6.png   1512    2016  3048192
2    f5003421985a7a5de8a4b36e073fd6ef.png   1512    2016  3048192
3    00ce72ef820369df798001e9a28bf34f.png   2016    1512  3048192
4    bf5c2516006cade6a0369cf28395f80d.png   1512    2016  3048192
..                                    ...    ...     ...      ...
173  93c642169ef5e111dde1b823fdc566a2.png   1831    1512  2768472
174  f2fa8ce472bd4021c533d9529c0d55b5.png   2016    1512  3048192
175  a221bc8a7db67f74a3379de0794ddcab.png   2016    1512  3048192
176  b2889436c6c0ed9d2a56f1ecda561798.png   1512    2016  3048192
177  aa8ada79ffbdcdb385aedf23bb89bebe.png   1512    2016  3048192

[178 rows x 4 columns]

             width       height       npixels
count   178.000000   178.000000  1.780000e+02
mean   1657.915730  1797.573034  2.936546e+06
std     295.589039   292.650478  4.023305e+05
min     540.000000   540.000000  5.184000e+05
25%    1512.000000  1512.000000  3.048192e+06
50%    1512.000000  2016.000000  3.048192e+06
75%    2016.000000  2016.000000  3.048192e+06
max    2048.000000  2016.000000  3.048192e+06